command_line:

  #ds processing mode (select one: RGB_STEREO, RGB_DEPTH)
  tracker_mode: RGB_STEREO

  #ds topic names
  topic_image_left:        /camera_left/image_raw
  topic_image_right:       /camera_right/image_raw
  
  #ds dataset file name
  dataset_file_name:

  #ds options
  option_use_gui:                   false
  option_use_odometry:              false
  option_disable_relocalization:    false
  option_show_top_viewer:           false
  option_drop_framepoints:          false
  option_equalize_histogram:        false
  option_recover_landmarks:         true
  option_disable_bundle_adjustment: true
  option_save_pose_graph:           false
  
  #topic synchronization
  maximum_time_interval_seconds:    0.01
  
landmark:

  #ds maximum measured distance kernel for landmark optimization
  maximum_error_squared_meters: 100

local_map:

  #ds target minimum number of landmarks for local map creation
  minimum_number_of_landmarks: 50
  
  #ds target maximum number of landmarks for local map creation
  maximum_number_of_landmarks: 1000

world_map:

  #ds key frame generation properties
  minimum_distance_traveled_for_local_map: 1.0
  minimum_degrees_rotated_for_local_map:   0.5
  minimum_number_of_frames_for_local_map:  4

base_framepoint_generation:

  #ds feature descriptor type (BRIEF-128/256/512, ORB-256, BRISK-512, FREAK-512, A-KAZE-486, BinBoost-064)
  descriptor_type: ORB-256

  #ds dynamic thresholds for feature detection
  target_number_of_keypoints_tolerance: 0.2
  detector_threshold_maximum_change:    0.2
  detector_threshold_minimum:           15
  detector_threshold_maximum:           30
  number_of_detectors_vertical:         2
  number_of_detectors_horizontal:       2

  #point tracking thresholds
  minimum_projection_tracking_distance_pixels: 15
  maximum_projection_tracking_distance_pixels: 50

  #ds dynamic thresholds for descriptor tracking
  minimum_descriptor_distance_tracking: 30
  maximum_descriptor_distance_tracking: 85

  #rigid stereo sensor configuration
  maximum_reliable_depth_meters: 10
  maximum_depth_meters:          1000
  minimum_depth_meters:          1
  
  #feature density regularization
  enable_keypoint_binning: true
  bin_size_pixels:         20

stereo_framepoint_generation:

  #ds stereo: triangulation
  maximum_matching_distance_triangulation: 90
  minimum_disparity_pixels:                1
  maximum_epipolar_search_offset_pixels:   0

tracking:

  #ds this criteria is used for the decision of whether creating a landmark or not from a track of framepoints
  minimum_track_length_for_landmark_creation: 2

  #ds track lost criteria
  minimum_number_of_landmarks_to_track: 5

  #point tracking thresholds
  tunnel_vision_ratio: 0.5
  good_tracking_ratio: 0.2

  #landmark track recovery (if enabled)
  maximum_number_of_landmark_recoveries: 10
  
  #ds motion model for initial pose guess (select one: NONE, CONSTANT_VELOCITY, CAMERA_ODOMETRY)
  motion_model: CONSTANT_VELOCITY

  #pose optimization
  minimum_delta_angular_for_movement:       0.001
  minimum_delta_translational_for_movement: 0.01
  
  #pose optimization: aligner unit configuration
  aligner->error_delta_for_convergence:  1e-3
  aligner->maximum_error_kernel:         4
  aligner->damping:                      5
  aligner->maximum_number_of_iterations: 1000
  aligner->minimum_number_of_inliers:    100
  aligner->minimum_inlier_ratio:         0
  aligner->enable_inverse_depth_as_information: true

relocalization:

  #maximum permitted descriptor distance to still be considered as a match
  maximum_descriptor_distance: 25

  #minimum query interspace
  preliminary_minimum_interspace_queries: 50

  #minimum relative number of matches
  preliminary_minimum_matching_ratio: 0.05

  #minimum absolute number of matches
  minimum_number_of_matched_landmarks: 25

  #correspondence retrieval
  minimum_matches_per_correspondence: 0
  
  #icp: aligner unit configuration
  aligner->error_delta_for_convergence:  1e-5
  aligner->maximum_error_kernel:         1.0
  aligner->damping:                      0.0
  aligner->maximum_number_of_iterations: 100
  aligner->minimum_number_of_inliers:    10
  aligner->minimum_inlier_ratio:         0.5

graph_optimization:

  #enable full bundle adjustment (default: only pose graph optimization upon loop closing)
  enable_full_bundle_adjustment: false

  #g2o factor graph optimization algorithm: GAUSS_NEWTON, LEVENBERG 
  optimization_algorithm: GAUSS_NEWTON

  #g2o linear solver type to perform optimization algorithm: CHOLMOD, CSPARSE
  linear_solver_type: CHOLMOD

  #g2o identifier space between frames and landmark vertices
  identifier_space: 1e9
  
  #maximum number of iterations graph optimization TODO proper termination criterion for GAUSS_NEWTON
  maximum_number_of_iterations: 10

  #determines window size for bundle adjustment
  number_of_frames_per_bundle_adjustment: 100

  #base frame weight in pose graph (assuming 1 for landmarks)
  base_information_frame: 1e5
  
  #free translation for pose to pose measurements
  free_translation_for_poses: true
  
  #translational frame weight reduction in pose graph
  base_information_frame_factor_for_translation: 1e-5

  #enable robust kernel for loop closure measurements
  enable_robust_kernel_for_poses: true

  #enable robust kernel for landmark measurements
  enable_robust_kernel_for_landmarks: false
  
  #minimum estimation correction to update the internal map
  minimum_estimation_delta_for_update_meters: 0.01

visualization:

  #follow robot in 3D map/trajectory viewer
  follow_robot: true

  #show secondary image
  display_secondary_image: false
